const WEB3_CONNECTED = 'WEB3_CONNECTED'
const LOTTERY_DEPLOYED = 'LOTTERY_DEPLOYED'

//const UNIQUE_PLAYERS = 'UNIQUE_PLAYERS'
//const TOTAL_WINNINGS = 'TOTAL_WINNINGS'

const GET_WINNERS = "GET_WINNERS"

export default {
    WEB3_CONNECTED,
    LOTTERY_DEPLOYED,
    GET_WINNERS
}