const WEB3_CONNECTED = 'WEB3_CONNECTED'
const LOTTERY_DEPLOYED = 'LOTTERY_DEPLOYED'

const UNIQUE_PLAYERS = 'UNIQUE_PLAYERS'
const TOTAL_WINNINGS = 'TOTAL_WINNINGS'

export default {
    WEB3_CONNECTED,
    LOTTERY_DEPLOYED,
    UNIQUE_PLAYERS,
    TOTAL_WINNINGS
}